# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'armhector'
    subscriptionId: 'd154b22a-00e9-4d61-bccd-1c77b06247da'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'armhector'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Zunderene/armhector/main/CreateWenApp/azuredeploy.json'
    overrideParameters: '-projectName armhector'
    deploymentMode: 'Incremental'